workflows:
  flutter-build:
    name: Build APK
    instance_type: mac_mini_m2
    environment:
      flutter: 3.22.0
    scripts:
      - name: Extract source
        script: unzip doa_rosario_hyperos3_flutter_source.zip
      - name: Get packages
        script: cd doa_rosario_hyperos3 && flutter pub get
      - name: Build APK
        script: cd doa_rosario_hyperos3 && flutter build apk --release
    artifacts:
      - doa_rosario_hyperos3/build/app/outputs/flutter-apk/app-release.apk
